# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmodel.proto\"%\n\x0cImageRequest\x12\x15\n\rinput_s3_uris\x18\x01 \x03(\t\"&\n\rImageResponse\x12\x15\n\routput_s3_uri\x18\x01 \x01(\t2?\n\x0eImageProcessor\x12-\n\x0cProcessImage\x12\r.ImageRequest\x1a\x0e.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=15
  _globals['_IMAGEREQUEST']._serialized_end=52
  _globals['_IMAGERESPONSE']._serialized_start=54
  _globals['_IMAGERESPONSE']._serialized_end=92
  _globals['_IMAGEPROCESSOR']._serialized_start=94
  _globals['_IMAGEPROCESSOR']._serialized_end=157
# @@protoc_insertion_point(module_scope)
